
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'].presence || 'localhost' %>
  username: <%= ENV['DATABASE_USER'].presence || 'music' %>
  password: <%= ENV['DATABASE_PASSWORD'].presence || 'cl0ckw0rk' %>

development:
  <<: *default
  database: clockwork_development

test:
  <<: *default
  database: clockwork_test

production:
  <<: *default
  database: clockwork_production
